###############################################################################################
#
# Input
# Required: Modify this section to provide inputs and cluster information
#
###############################################################################################

Input:
  prefix: placeholder           # [value] output files will be prefixed with this name
  genome: placeholder           # [file] gzipped genome assembly fasta file (genome.fa.gz)
  rna_seq: placeholder          # [directory] folder containing RNA-seq data. Files should be gzipped
                                # fastq (i.e. fastq.gz)
  proteins: placeholder         # Comma separated list of protein fasta files for homology search
  singularity: placeholder      # [file/directory] the singularity image or sandbox
  liftoff:                              
    neighbor_gff: placeholder     # [directory] folder containing neighbor species annotations (GFF3)
    neighbor_fasta: placeholder   # [directory] folder containing neighbor species genomes (fasta)
  helixer_model: placeholder      # [value] appropriate helixer lineage (land_plant, vertebrate, invertebrate, fungi)
  helixer_subseq: 64152        # [value] helixer subsequence length (21384:fungi, 64152:plants, or 213840:vertebrates)
  geta:
    RM_species: Embryophyta       # [value] chose a Repeat Modeler species (i.e. Embryophyta)
    RM_lib: placeholder           # [file] A fasta file containing pre-computed repeat sequences. (Repeat modeler training will be skipped.)
    dfam_lib: placeholder         # [file] the DFAM lib
    geta_conf: big                # [value] chose a geta configuration mode (big/small)
    pfamdb: /usr/local/src/Pfam-A.hmm               # [file] pfam database file (i.e. pfam.hmm)
    augustus_species: placeholder     # [value] chose an augustus species or use a custom name
    use_augustus: placeholder         # Species identifier for Augustus. This parameter conflicts with
                                      # augustus_species. When this parameter set, the augustus_species
                                      # parameter will be invalid, and the relative hmm files of augustus
                                      # training must exist, and the augustus training step will be skipped
                                      # (this will save lots of running time).
    augustus_start_from: placeholder    # Species identifier for Augustus. The optimization step of Augustus 
                                      # training will start from the parameter file of this species, may save runtime.
  evm_weights: placeholder            # Must provide absolute path to evm weights file (/.../config/evm_weights.txt)
  num_evm_files: 126                  # Number of EVM splits 

###############################################################################################
#
# Cluster Configuration
# [Required] Configure cluster with account information
# [Optional] modify resource allocation and threading for specific processes 
#
###############################################################################################

__default__:
  account: placeholder                  # SLURM account
  partition: placeholder                # SLURM partition
  memory: 4g
  name: JOB.{rule}.{wildcards}
  ncpus: 1
  nodes: 1
  time: 14-00:00:00
  output: logs/{rule}.{wildcards}.out
  error: logs/{rule}.{wildcards}.err
helixer:
  #account: placeholder                # SLURM gpu account
  #partition: placeholder              # SLURM gpu parition
  ncpus: 12
  threads: 12
  memory: 48g
liftoff:
  ncpus: 24
  threads: 24
  memory: 96g
miniprot: 
  ncpus: 54
  threads: 54
  memory: 216g
gmapPrep:
  ncpus: 4
  memory: 16g
gmapExon: 
  ncpus: 16
  threads: 16
  memory: 64g
bam2Fasta:
  ncpus: 32
  threads: 32
  memory: 124g
spades:
  ncpus: 48
  threads: 48
  memory: 192g
evigene:
  ncpus: 12
  threads: 12
  memory: 48g
pasaPrep:
  ncpus: 4
  memory: 16g
pasa:
  ncpus: 32
  threads: 32
  memory: 128g
addXS:
  ncpus: 12
  memory: 48g
psiClass_HiSat:
  ncpus: 4
  threads: 4
  memory: 16g
stringtie_HiSat:
  ncpus:  54
  threads: 32
  memory: 216g
psiClass_STAR:
  ncpus:  54
  threads: 4
  memory: 216g
stringtie_STAR:
  ncpus:  54
  threads: 32
  memory: 216g
bamToFastq:
  ncpus:  12
  threads: 12
  memory: 48g
STAR_generate:
  ncpus:  12
  threads: 12
  memory: 48g
STAR_paired:
  ncpus:  54
  threads: 54
  memory: 216g
STAR_single:
  ncpus: 54
  threads: 54
  memory: 216g
mergeSTAR:
  ncpus: 12
  threads: 12
  memory: 48g
convertToEvmFormat:
  ncpus: 1
  memory: 4g
combineEVMInputs:
  ncpus: 1
  memory: 4g
partitionEVM:
  ncpus: 12
  memory: 48g
writeEVMCommands:
  ncpus: 4
  memory: 16g
runEVM:
  ncpus: 1
  memory: 4g
recombineEVM:
  ncpus: 4
  memory: 16g
pasaPost:
  ncpus: 54
  threads: 54
  memory: 216g
RepeatMasker_species:
  ncpus: 4
  threads: 4
  memory: 16g
RepeatModeler:
  ncpus: 4
  threads: 4
  memory: 16g
RepeatMasker_custom:
  ncpus: 4
  threads: 4
  memory: 16g
RepeatMasker_merge:
  ncpus: 4
  threads: 4
  memory: 16g
fastp_PAIRED:
  ncpus: 8
  threads: 8
  memory: 32g
fastp_SINGLE:
  ncpus: 8
  threads: 8
  memory: 32g
HiSat2_split:
  ncpus: 56
  threads: 14
  memory: 224g
HiSat2_build:
  ncpus: 4
  memory: 16g
HiSat2_PAIRED:
  ncpus: 16
  threads: 16
  memory: 64g
HiSat2_SINGLE:
  ncpus: 16
  threads: 16
  memory: 64g
mergeHiSat:
  ncpus: 54
  threads: 58
  memory: 216g
  sortthreads: 8
  sortmem: 16G
Sam2Transfrag:
  ncpus: 4
  memory: 16g
mergeTransfrag:
  ncpus: 4
  memory: 16g
transDecoder_LongOrfs:
  ncpus: 4
  memory: 16g
transDecoder_Predict:
  ncpus: 4
  memory: 16g
transdecoder2ORF:
  ncpus: 4
  memory: 16g
GFF3Clear:
  ncpus: 4
  memory: 16g
transfragComplete:
  ncpus: 4
  memory: 16g
ORF2bestGeneModels:
  ncpus: 4
  memory: 16g
bestGeneModels2lowIdentity:
  ncpus: 4
  threads: 4
  memory: 16g
genomeSplitJoin:
  ncpus: 2
  memory: 8g
mergeProteins:
  ncpus: 4
  threads: 4
  memory: 16g
createMMseqsNucDB:
  ncpus: 4
  memory: 16g
splitProteins:
  ncpus: 4
  threads: 4
  memory: 16g
createMMseqsProtDB:
  ncpus: 4
  memory: 16g
MMseqs:
  ncpus: 16
  threads: 4
  memory: 64g
mergeMMseqs:
  ncpus: 1
  memory: 4g
blast2GeneRegion:
  ncpus: 8
  memory: 32g
prep_geneRegion2Genewise:
  ncpus: 1
  memory: 4g
merge_geneRegion2Genewise:
  ncpus: 1
  memory: 4g
geneRegion2Genewise:
  ncpus: 4
  threads: 4
  memory: 16g
genewiseGFF2GFF3:
  ncpus: 4
  memory: 16g
combineGeneModelsPlus:
  ncpus: 4
  memory: 16g
combineGeneModelsMinus:
  ncpus: 4
  memory: 16g
aggregate_CombineGeneModels:
  ncpus: 4
  memory: 16g
clearCombined:
  ncpus: 4
  memory: 16g
geneModels2AugusutsTrainingInput:
  ncpus: 4
  threads: 4
  memory: 16g
BGM2AT:
  ncpus: 54
  threads: 8
  memory: 208g
prepareAugusutusHints:
  ncpus: 4
  memory: 16g
augustusWithHints:
  ncpus: 4
  memory: 16g
combineAugustusWithHints:
  ncpus: 4
  memory: 16g
combineGeneModelsPlus_step6:
  ncpus: 4
  memory: 16g
combineGeneModelsMinus_step6:
  ncpus: 4
  memory: 16g
aggregate_CombineGeneModels_step6:
  ncpus: 4
  memory: 16g
clearCombined_step6:
  ncpus: 4
  memory: 16g
pickBetterModels:
  ncpus: 4
  memory: 16g
fillingEndsOfGeneModels_ef:
  ncpus: 4
  memory: 16g
AS_gb:
  ncpus: 4
  memory: 16g
aggregateAS_gb:
  ncpus: 4
  memory: 16g
AS_ge:
  ncpus: 4
  memory: 16g
aggregateAS_ge:
  ncpus: 4
  memory: 16g
AS_gf:
  ncpus: 4
  memory: 16g
aggregateAS_gf:
  ncpus: 4
  memory: 16g
extractTranscriptsForFilter:
  ncpus: 4
  memory: 16g
splitFilterProteins:
  ncpus: 4
  memory: 16g
filterHMMScan:
  ncpus: 4
  threads: 4
  memory: 16g
combineHMMScan:
  ncpus: 4
  memory: 16g
makeFilterBlastDB:
  ncpus: 4
  threads: 4
  memory: 16g
filterBlastP:
  ncpus: 4
  threads: 4
  memory: 16g
parseBlastResult:
  ncpus: 4
  memory: 16g
validateTranscripts:
  ncpus: 4
  memory: 16g
fillingEndsOfGeneModels_final:
  ncpus: 4
  memory: 16g
GETA_output:
  ncpus: 4
  memory: 16g
portcullis:
  ncpus: 12
  threads: 12
  memory: 48g
mikadoConfigure:
  ncpus: 1
  memory: 4g
mikadoPrepare:
  ncpus: 1
  memory: 4g
mikadoMakeDB:
  ncpus: 1
  memory: 4g
mikadoBlastX:
  ncpus: 16
  threads: 16
  memory: 64g
mikadoTransdecoder_LongOrfs:
  ncpus: 4
  threads: 4
  memory: 16g
mikadoTransdecoder_Predict:
  ncpus: 4
  threads: 4
  memory: 16g
mikadoSerialise:
  ncpus: 4
  memory: 16g
mikadoPick:
  ncpus: 4
  memory: 16g
EvidentialCombine:
  ncpus: 16 
  memory: 64g

###############################################################################################
#
# [Careful!] Arguments for internal processing. Edit with caution
#
###############################################################################################

Internal:
  RepeatMasker: -e ncbi -gff
  hisat2-build: -p 1
  hisat2: --min-intronlen 20 --max-intronlen 20000 --dta --score-min L,0.0,-0.4
  sam2transfrag: --fraction 0.05 --min_expressed_base_depth 2 --max_expressed_base_depth 50 --min_junction_depth 2 --max_junction_depth 50 --min_fragment_count_per_transfrags 10 --min_intron_length 20
  TransDecoder.LongOrfs: -m 100 -G universal
  TransDecoder.Predict: --retain_long_orfs_mode dynamic
  homolog_genewise: --coverage_ratio 0.4 --evalue 1e-9
  homolog_genewiseGFF2GFF3: --min_score 100 --gene_prefix genewise --filterMiddleStopCodon
  geneModels2AugusutsTrainingInput: --min_evalue 1e-9 --min_identity 0.8 --min_coverage_ratio 0.8 --min_cds_num 2 --min_cds_length 450 --min_cds_exon_ratio 0.60
  BGM2AT: --min_gene_number_for_augustus_training 500 --gene_number_for_accuracy_detection 200 --min_gene_number_of_optimize_augustus_chunk 50 --max_gene_number_of_optimize_augustus_chunk 200
  prepareAugusutusHints: --margin 20
  paraAugusutusWithHints: --gene_prefix augustus --min_intron_len 20 --alternatives_from_evidence
  paraCombineGeneModels: --overlap 30 --min_augustus_transcriptSupport_percentage 10.0 --min_augustus_intronSupport_number 1 --min_augustus_intronSupport_ratio 0.01
  PfamValidateABinitio: --CDS_length 750 --CDS_num 2 --evalue 1e-5 --coverage 0.25
  remove_genes_in_repeats: --ratio 0.8
  remove_short_genes: --cds_length 150%
  ORF2bestGeneModels: --min_cds_num 3 --min_cds_length 900 --min_cds_exon_ratio 0.60 --intron_length_fractile 0.95 --cds_length_fractile 0.95
  alternative_splicing_analysis: --min_intron_depth 1 --min_base_depth_ratio_for_ref_specific_intron 0.3 --min_intron_depth_ratio_for_evidence_specific_intron 0.2 --min_base_depth_ratio_for_common_intron 0.2 --min_gene_depth 10 --min_transcript_confidence_for_output 0.05 --transcript_num_for_output_when_all_low_confidence 8 --added_mRNA_ID_prefix t
  GFF3_extract_TranscriptID_for_filtering: --min_CDS_ratio 0.3 --min_CDS_length 600 --max_repeat_overlap_ratio 0.3 --ignore_repeat_Name Simple_repeat,Low_complexity,Satellite,Unknown,Tandem_repeat
  para_hmmscan: --evalue1 1e-5 --evalue2 1e-3 --hmm_length 80 --coverage 0.25 --no_cut_ga --chunk 20 --hmmscan_cpu 2
  diamond: --sensitive --max-target-seqs 20 --evalue 1e-5 --id 10 --index-chunks 1 --block-size 5
  parsing_blast_result.pl: --evalue 1e-9 --identity 0.1 --CIP 0.4 --subject-coverage 0.4 --query-coverage 0.4
  get_valid_geneModels: --discard_Filling2Uncomplete
  get_valid_transcriptID: --hmm_evalue 1e-20 --hmm_coverage 0.8 --blast_evalue 1e-20 --blast_CIP 0.8 --blast_coverage 0.8 --blast_evalue_for_genesie 1e-10 --blast_CIP_for_genewise 0.8 --blast_coverage_for_genewise 0.9 # add --both_required for more strcit.
  fillingEndsOfGeneModels: --start_codon ATG --stop_codon TAG,TGA,TAA
  pickout_better_geneModels_from_evidence: --overlap_ratio 0.2 --ratio1 2 --ratio2 1.5 --ratio3 0.85 --ratio4 0.85
  parsing_blast_result: --evalue 1e-10 --identity 0.1 --CIP 0.5 --subject-coverage 0.5 --query-coverage 0.5
