###############################################################################################
#
# Input
# [Required] Provide input to GeneModelFilter
#
###############################################################################################

Singularity: placeholder

Input:
  genome: ./GETA/genome.fasta
  rna_seq: placeholder                              # Directory with paired-end RNAseq data
  protein: ./PROTEIN/merged_rmdup_proteins.fasta    # Homolg protein file [path/to/proteins.fasta]
  anot_gff: ./complete_draft.gff3                   # Annotated gff
  augustus_gff: ./GETA/Augustus/augustus.gff3       # Augustus annotation
  helixer_gff: placeholder                          # Helixer annotation (./AB_INITIO/Helixer/[prefix]_helixer.gff3)
  repeat_gff: placeholder                           # Repeat annotation
  HmmDB: /usr/local/src/Pfam-A.hmm                  # PFAM direcory for pfam scanning [path/to/HMM_Lib/]
  RexDB: placeholder                                # RexDB file
  chrom_regex: (^Chr)|(^chr)|(^LG)|(^Ch)|(^\d)      # Regex string capturing the prefix of all chromosomes 

###############################################################################################
#
# Filter Configuration
# [Optional] Configure GeneModelFilter
#
###############################################################################################

Cutoff:
  fpkm: 3                  # Expression cutoff threshold (keep genes greater than)
  rsem_cov: 0.5            # RSEM coverage cutoff (keep genes greater than)
  blast_pident: 0.6        # Blast percent identity (default: 0.6) (keep genes greater than)
  blast_qcovs: 0.6         # Blast query coverage (default: 0.6) (keep genes greater than)
  rex_pident: 0.6          # RexDB blast percent identity (default: 0.6) (keep genes less than)
  rex_qcovs: 0.6           # RexDB blast query coverage (default: 0.6) (keep genes less than)
  helixer_cov: 0.8         # Helixer coverage cutoff (keep genes greater than)
  augustus_cov: 0.8        # Augustus coverage cutoff (keep genes greater than)
  repeat_cov: 0.5          # Repeat coverage cutoff (keep genes less than)

###############################################################################################
#
# Cluster Configuration
# [Required] Configure cluster
#
###############################################################################################
 
Threads:
  PfamScan: 48
  sortSTAR: 16
  blast: 16
  STAR_generate: 12
  fastp_PAIRED: 16
  prepRSEM: 16
  STAR: 12
  mergeSTAR: 16
  calculateRSEMExpression: 16
  lncRNA_pred: 48
  STAR_index: 12


__default__:
  account: placeholder
  partition: placeholder
  memory: 16g
  name: JOBNAME.{rule}.{wildcards}
  ncpus: 4
  nodes: 1
  time: 7-00:00:00
  output: logs/{rule}.{wildcards}.out
  error: logs/{rule}.{wildcards}.err
PfamScan:
  ncpus: 48
  memory: 192g
RSEM:
  ncpus: 32
  memory: 128g
sortSTAR:
  ncpus: 16
  memory: 64g
blast:
  ncpus: 16
  memory: 64g
coverage:
  ncpus: 16
  memory: 64g
indexRef:
  ncpus: 4
  memory: 16g
blastDB:
  ncpus: 4
  memory: 16g
splitPep:
  ncpus: 4
  memory: 16g
combineBlast:
  ncpus: 4
  memory: 16g
abInitioCoverage:
  ncpus: 1
  memory: 4g
STAR_generate:
  ncpus: 12
  memory: 48g
fastp_PAIRED:
  ncpus: 16
  memory: 64g
STAR_paired:
  ncpus: 12
  memory: 48g
mergeSTAR:
  ncpus: 16
  memory: 64g
calculateRSEMExpression:
  ncpus: 16
  memory: 64g
prepRSEM:
  ncpus: 16
  memory: 64g
lncRNA_pred:
  ncpus: 48
  memory: 192g
STAR_index:
  ncpus: 12
  memory: 48g
